#!/usr/bin/env python3
"""Deterministic size/class planner for Ultimate Fish tablebases.

This planner deliberately reports conservative *uncompressed* sizes for the
v3 split-plane format.  The generator may make files smaller, but it must not
use optimistic compression ratios when deciding whether the repository's
original 10 GiB target has already been exhausted. Two explicitly requested
classes are then accounted for against a separate narrow overrun ceiling.
"""

from __future__ import annotations

import argparse
import itertools
import json
from dataclasses import dataclass


FILES = 8
RANKS = 10
SQUARES = FILES * RANKS
GITHUB_FILE_LIMIT = 100_000_000
# Leave a full 5 MB safety margin below GitHub's decimal 100 MB hard limit.
DEFAULT_SHARD_LIMIT = 95_000_000
DEFAULT_BUDGET = 10 * 1024**3
# Preserve the historically selected repository classes while exact causal
# Penguin membership expands their logical payloads.  Most completed outputs
# will be served from S3, so this is now a 12 GiB planning ceiling rather than
# a promise that every logical payload will be committed to Git.
AUTHORIZED_BUDGET = 12 * 1024**3


@dataclass(frozen=True)
class Piece:
    name: str
    decisive: bool = False
    minor: bool = False
    color_bound: bool = False
    support: bool = False
    state_factor: int = 1
    models: int = 1
    stateless: bool = True
    closed_k2: bool = True
    note: str = ""


# Generated-only Goop, Minion, CheckerKing, CopycatClone, and Halo are encoded
# as state of their deployable parent rather than treated as draft material.
PIECES = (
    Piece("jester", decisive=True),
    Piece("knight", minor=True),
    Piece("pawn", decisive=True, state_factor=2, stateless=False,
          note="moved flag; promotion crosses into Queen tables"),
    Piece("queen", decisive=True),
    Piece("rook", decisive=True),
    Piece("bishop", color_bound=True),
    Piece("berserker", decisive=True, state_factor=10, stateless=False,
          note="power 0..8 plus board-saturating 9+ equivalence bucket"),
    Piece("bomb", decisive=True),
    Piece("ninja", decisive=True),
    Piece("turtle", minor=True),
    Piece("ghost", decisive=True, state_factor=2, stateless=False,
          note="visible/hidden"),
    Piece("mage", support=True),
    Piece("penguin", decisive=True, state_factor=4, stateless=False,
          note="exact causal freeze membership for both Kings and any companion"),
    Piece("parasite", decisive=True),
    Piece("devil", decisive=True, state_factor=4, stateless=False,
          closed_k2=False,
          note="sufficient via spawned Minions; spawned-only closure admits no Minions "
               "except those generated by the indexed Devil"),
    Piece("sludge", stateless=False, closed_k2=False,
          note="insufficient alone; generated Goop belongs to larger closures"),
    Piece("sniper", decisive=True, state_factor=4, stateless=False,
          note="cooldown 0..3"),
    Piece("prince", decisive=True, state_factor=2, stateless=False,
          note="ordinary/forced-second-action phase"),
    Piece("checker", color_bound=True, state_factor=4, stateless=False,
          note="Checker/CheckerKing type and ordinary/forced-jump phase"),
    Piece("giant", decisive=True,
          note="2x2 footprint makes some anchor tuples invalid"),
    Piece("copycat", decisive=True, stateless=False, closed_k2=False,
          note="linked mirror clone is position-derived until an external effect displaces it"),
    Piece("angel", support=True, state_factor=2, stateless=False,
          closed_k2=False,
          note="insufficient alone; exact one-Angel deployed/attached/Halo codec"),
    Piece("fisherman", support=True),
    Piece("dragon", decisive=True),
)

DEFERRED_DYNAMIC_K2 = frozenset({"sludge"})
COPYCAT_SEPARATORS = frozenset({"penguin", "mage", "fisherman"})
# The v9/v10 Angel graph codecs cover one-Angel public-information domains.
# Angel/Angel has no attacking material and is an exact closed-form draw, so
# its ordered rescue stack never needs indexing. Ghost/Angel's concrete v9
# graph is in scope; publication still requires a perfect-recall attachment
# information overlay. Jester/Angel is closed by the v9 Angel graph plus the
# primary-Jester public-observation overlay. Same-team
# Copycat/Angel uses the v10
# four-host-mode graph plus an exact arbitrary-linked-pair lower table.
ANGEL_DEFERRED_COMPANIONS = frozenset({
    "sludge", "angel",
})


def deferred_material(first: str, second: str = "", *,
                      opposing: bool = False) -> bool:
    """Return whether this material lies outside the exact campaign codecs."""
    names = {first, second} - {""}
    # The approved Devil campaign is a closed spawned-material simplification:
    # every indexed Devil starts on ranks 1-3, and only Minions spawned by an
    # indexed Devil may enter the closure.  It applies to every Devil pairing,
    # including Devil/Sludge; arbitrary pre-existing Minions remain excluded.
    if "devil" in names:
        return False
    if first == "devil" and not second:
        return False
    if names & DEFERRED_DYNAMIC_K2:
        return True
    if "angel" in names:
        if not second:
            return False
        companion = second if first == "angel" else first
        if companion == "angel":
            return False
        if companion in ANGEL_DEFERRED_COMPANIONS:
            return True
    return "copycat" in names and bool(names & COPYCAT_SEPARATORS)


def placement_states(extra_models: int, identical_pair: bool = False) -> int:
    """Dense states after exact horizontal-reflection canonicalization.

    The Ivory King is restricted to files a-d. Remaining labelled models use
    a falling factorial. Two same-type, same-team extras are interchangeable.
    """
    result = 2 * (SQUARES // 2)  # side to move, canonical Ivory King
    available = SQUARES - 1
    for _ in range(1 + extra_models):  # Onyx King plus extra board models
        result *= available
        available -= 1
    if identical_pair:
        result //= 2
    return result


def compound_copycat_pair_states(identical_pair: bool = False) -> int:
    """K+linked-Copycat vs K+piece states without reflection folding.

    The Copycat's second board model is derived from the indexed half, so only
    four logical squares are stored.  Horizontal reflection exchanges the two
    typed halves, however, so this codec deliberately retains both orbits just
    like the existing K+Copycat-v-K table.
    """
    result = 2 * SQUARES * (SQUARES - 1) * (SQUARES - 2) * (SQUARES - 3)
    return result // 2 if identical_pair else result


def linked_copycat_pair_states() -> int:
    """K+arbitrarily displaced reciprocal Copycat pair versus King.

    Angel rescue can move the struck half to its Halo while leaving the linked
    partner in place. Both explicit half squares are horizontally folded.
    """
    return placement_states(2)


def material_state_factor(piece: Piece, *, four_models: bool = False,
                          other: Piece | None = None) -> int:
    """Return the exact substate factor in this material domain.

    A Penguin records which adjacent pieces it actually froze on its preceding
    move.  Later movement can enter an active Penguin's neighbourhood without
    joining that causal set, so geometry alone cannot recover the state.  Two
    King membership bits give four K+Penguin-v-K substates.  A distinct fourth
    model adds one bit; another Penguin is immune and adds no target bit.
    """
    if piece.name != "penguin":
        return piece.state_factor
    if not four_models or other is None or other.name == "penguin":
        return 4
    return 8


def pair_state_factor(first: Piece, second: Piece) -> int:
    return (material_state_factor(first, four_models=True, other=second) *
            material_state_factor(second, four_models=True, other=first))


def angel_pair_state_factor(companion: Piece, same_team: bool) -> int:
    """Exact one-Angel topology factor for a K+K+2 material class.

    An opposed Angel has two modes: deployed or attached to its own King.  A
    same-team Angel ordinarily has a third mode in which it is attached to the
    companion. Copycat has two independently protectable linked halves, so its
    same-team graph has four modes.
    The dense Angel slot stores the deployed square or the live Halo square, so
    the ordinary four-model placement count remains valid.
    """
    angel = next(piece for piece in PIECES if piece.name == "angel")
    return (((4 if companion.name == "copycat" else 3)
             if same_team else 2) *
            material_state_factor(companion, four_models=True, other=angel))


def single_material_states(piece: Piece) -> int:
    """Exact K+piece-v-K codec size; this codec retains both reflections."""
    return 2 * placement_states(piece.models) * material_state_factor(piece)


def split_plane_bytes(states: int) -> int:
    # Two-bit WDL plus one-byte DTW. Rare DTW>=255 exceptions are placed in a
    # separate shard and intentionally excluded from this baseline estimate.
    return (states + 3) // 4 + states


def sufficient_pair(first: Piece, second: Piece, same_team: bool) -> bool:
    if not same_team:
        return first.decisive or second.decisive
    if first.decisive or second.decisive:
        return True
    if first.minor and second.minor:
        return True
    if (first.minor and second.color_bound) or (second.minor and first.color_bound):
        return True
    if (first.support and second.color_bound) or (second.support and first.color_bound):
        return True
    # Two color-bound pieces can occupy opposite square colors, so retain the
    # whole material class even though same-color placements are drawn.
    return first.color_bound and second.color_bound


def class_record(name: str, states: int, phase: str, note: str = "",
                 primary: str = "", secondary: str = "",
                 opposing: bool = False, filename: str = "") -> dict[str, object]:
    size = split_plane_bytes(states)
    return {
        "class": name,
        "phase": phase,
        "states": states,
        "packed_bytes": size,
        "shards": (size + DEFAULT_SHARD_LIMIT - 1) // DEFAULT_SHARD_LIMIT,
        "note": note,
        "primary": primary,
        "secondary": secondary,
        "opposing": opposing,
        "filename": filename,
    }


def stateful_candidates() -> list[dict[str, object]]:
    """Closed K+K+2 classes containing at least one stateful character.

    Spawning, attachment, and linked-multi-model characters are deliberately
    excluded: their exact closure is larger than four board models and cannot
    truthfully be represented by this codec. Candidate order gives every
    closed stateful type one same-team Bomb class before spending the
    remaining budget on the smallest classes. Bomb keeps this coverage tier's
    predecessor graphs much smaller than an equally sized Queen pairing.
    """
    closed = tuple(piece for piece in PIECES if piece.closed_k2)
    result: list[dict[str, object]] = []
    for first_index, first in enumerate(closed):
        for second in closed[first_index:]:
            if first.stateless and second.stateless:
                continue
            factor = pair_state_factor(first, second)
            if sufficient_pair(first, second, True):
                states = placement_states(
                    first.models + second.models,
                    first == second and first.models == 1) * factor
                result.append(class_record(
                    f"K{first.name}{second.name}vK", states, "kings+2-stateful",
                    primary=first.name, secondary=second.name,
                    filename=f"k{first.name}{second.name}k.uftb"))
            if sufficient_pair(first, second, False):
                states = placement_states(first.models + second.models) * factor
                result.append(class_record(
                    f"K{first.name}vK{second.name}", states, "kings+2-stateful",
                    primary=first.name, secondary=second.name, opposing=True,
                    filename=f"k{first.name}k{second.name}.uftb"))

    stateful_names = {piece.name for piece in closed if not piece.stateless}
    coverage = {
        (name, "bomb", False) for name in stateful_names
    } | {
        ("bomb", name, False) for name in stateful_names
    }
    return sorted(result, key=lambda record: (
        (str(record["primary"]), str(record["secondary"]), bool(record["opposing"]))
        not in coverage,
        int(record["packed_bytes"]), str(record["filename"])))


def angel_candidates() -> list[dict[str, object]]:
    """Return exact visible Angel K+K+2 computation domains.

    Insufficient pairings are intentionally absent: the ledger records those
    as closed-form draws. Unsupported multi-rescue and spawning topologies
    remain explicit deferrals. Ghost/Angel is admitted as a concrete source
    graph but remains ``information required`` until its perfect-recall
    attachment overlay is certified. The same-team Copycat graph is admitted
    only with its exact displaced-pair lower dependency.
    """
    order = {piece.name: index for index, piece in enumerate(PIECES)}
    angel = next(piece for piece in PIECES if piece.name == "angel")
    result: list[dict[str, object]] = []
    for companion in PIECES:
        if (companion.name in ANGEL_DEFERRED_COMPANIONS or
                companion.name == "devil" or
                companion.name == "copycat"):
            continue
        first, second = sorted((companion, angel),
                               key=lambda piece: order[piece.name])
        if sufficient_pair(first, second, True):
            states = (placement_states(2) *
                      angel_pair_state_factor(companion, True))
            result.append(class_record(
                f"K{first.name}{second.name}vK", states,
                "kings+2-angel-graph-v1", primary=first.name,
                secondary=second.name,
                filename=f"k{first.name}{second.name}k.uftb",
                note="exact one-Angel deployed/attached/host/Halo graph"))
        if sufficient_pair(first, second, False):
            states = (placement_states(2) *
                      angel_pair_state_factor(companion, False))
            result.append(class_record(
                f"K{first.name}vK{second.name}", states,
                "kings+2-angel-graph-v1", primary=first.name,
                secondary=second.name, opposing=True,
                filename=f"k{first.name}k{second.name}.uftb",
                note="exact one-Angel deployed/attached/host/Halo graph"))
    result.append(class_record(
        "KcopycatvKangel", compound_copycat_pair_states() * 2,
        "kings+2-angel-graph-v1", primary="copycat", secondary="angel",
        opposing=True, filename="kcopycatkangel.uftb",
        note=("exact opposed Angel deployed/attached-to-own-King graph with "
              "an intact linked-mirror Copycat compound")))
    result.append(class_record(
        "KcopycatangelvK", compound_copycat_pair_states() * 4,
        "kings+2-angel-copycat-graph-v1", primary="copycat",
        secondary="angel", filename="kcopycatangelk.uftb",
        note=("exact deployed/own-King/primary-half/clone-half Angel graph; "
              f"rescue enters {linked_copycat_pair_states():,}-state exact "
              "arbitrary-linked-Copycat lower table")))
    if len(result) != 32 or len({str(row["filename"]) for row in result}) != 32:
        raise RuntimeError("visible one-Angel K+K+2 inventory residual")
    return sorted(result, key=lambda record: str(record["filename"]))


def devil_pair_starting_geometries(*, identical_same_team: bool) -> int:
    """Exact indexed K+K+2 Devil starting geometries.

    The Ivory King is horizontally canonicalized, while both Kings remain
    ordinary board models.  Every Devil is immobile and therefore starts on
    ranks 1-3.  This is the exact starting frontier only; spawned Minion states
    belong to the sparse closure and are deliberately not estimated as a dense
    Cartesian product.
    """
    result = 0
    devil_squares = set(range(FILES * 3))
    for ivory in range(SQUARES):
        if ivory % FILES >= FILES // 2:
            continue
        for onyx in range(SQUARES):
            if onyx == ivory:
                continue
            available = len(devil_squares - {ivory, onyx})
            if identical_same_team:
                result += available * (available - 1) // 2
            else:
                # One Devil plus a labelled companion.  For Devil/Devil with
                # opposing owners, the companion is also restricted below.
                result += available * (SQUARES - 3)
    return 2 * result


def devil_candidates() -> list[dict[str, object]]:
    """Return every approved spawned-only Devil K+K+2 planning domain."""
    order = {piece.name: index for index, piece in enumerate(PIECES)}
    devil = next(piece for piece in PIECES if piece.name == "devil")
    result: list[dict[str, object]] = []
    for companion in PIECES:
        first, second = sorted((companion, devil),
                               key=lambda piece: order[piece.name])
        for opposing in (False, True):
            if companion.name == "devil":
                if opposing:
                    # Both owner-labelled Devils are restricted to ranks 1-3.
                    geometry = 0
                    devil_squares = set(range(FILES * 3))
                    for ivory in range(SQUARES):
                        if ivory % FILES >= FILES // 2:
                            continue
                        for onyx in range(SQUARES):
                            if onyx == ivory:
                                continue
                            available = len(devil_squares - {ivory, onyx})
                            geometry += available * (available - 1)
                    geometry *= 2
                else:
                    geometry = devil_pair_starting_geometries(
                        identical_same_team=True)
            else:
                geometry = devil_pair_starting_geometries(
                    identical_same_team=False)
            factor = pair_state_factor(first, second)
            if companion.name == "angel":
                factor = (3 if not opposing else 2) * devil.state_factor
            states = geometry * factor
            result.append(class_record(
                (f"K{first.name}{second.name}vK" if not opposing else
                 f"K{first.name}vK{second.name}"),
                states, "devil-spawned-pair-closure-v1",
                primary=first.name, secondary=second.name,
                opposing=opposing,
                filename=(f"k{first.name}{second.name}k.uftb" if not opposing
                          else f"k{first.name}k{second.name}.uftb"),
                note=("indexed Devil(s) start on ranks 1-3; sparse closure "
                      "admits only Minions spawned by an indexed Devil and "
                      "no arbitrary pre-existing Minions"),
            ))
    if len(result) != 48 or len({str(row["filename"]) for row in result}) != 48:
        raise RuntimeError("Devil K+K+2 planning inventory residual")
    return sorted(result, key=lambda record: str(record["filename"]))


def mirror_copycat_candidates() -> list[dict[str, object]]:
    """User-approved linked-mirror K+K+2 Copycat planning domain.

    One indexed Copycat half implies its exact horizontal-mirror clone, as in
    the bundled K+Copycat-v-K and K+Copycat-v-K+Bishop tables. Starting states
    therefore contain only unsplit linked pairs. Devil/Sludge/Angel remain
    deferred wholesale, while Penguin, Mage, and Fisherman are omitted because
    they can split a pair within this material class. Every retained class is
    closed under the unsplit-pair invariant; no displaced child is scored as a
    draw or silently discarded.
    """
    result: list[dict[str, object]] = []
    for secondary in PIECES:
        if secondary.name in (DEFERRED_DYNAMIC_K2 | COPYCAT_SEPARATORS |
                              {"angel", "devil"}):
            continue
        for opposing in (False, True):
            states = compound_copycat_pair_states(
                identical_pair=secondary.name == "copycat" and not opposing
            ) * secondary.state_factor
            record = class_record(
                (f"Kcopycat{secondary.name}vK" if not opposing else
                 f"KcopycatvK{secondary.name}"),
                states, "kings+2-copycat-mirror",
                primary="copycat", secondary=secondary.name,
                opposing=opposing,
                filename=(f"kcopycat{secondary.name}k.uftb" if not opposing else
                          f"kcopycatk{secondary.name}.uftb"),
                note=("linked horizontal-mirror Copycat compound; "
                      "singleton/independently displaced states excluded"),
            )
            record["mirror_simplification"] = True
            record["truncates_native_separation"] = False
            result.append(record)
    if len(result) != 36 or len({str(row["filename"]) for row in result}) != 36:
        raise RuntimeError("mirror Copycat K+K+2 inventory residual")
    return sorted(result, key=lambda record: str(record["filename"]))


def inventory(budget: int = DEFAULT_BUDGET) -> list[dict[str, object]]:
    result: list[dict[str, object]] = []
    for piece in PIECES:
        if not piece.decisive:
            continue
        states = single_material_states(piece)
        phase = "kings+1"
        note = piece.note
        if piece.name == "devil":
            # The preserved UFTB uses the complete dense K+Devil-v-K codec so
            # placements outside the legal first-three-ranks root domain are
            # explicit excluded sentinels.  The seeded starting frontier is
            # exactly three tenths of this indexed extent (1,183,104 states),
            # while spawned Minions live only in the fixed-square proof graph.
            phase = "devil-spawned-closure-v3"
            note = (piece.note + "; dense root table retains explicit excluded "
                    "sentinels outside the first three ranks")
        single_filename = {"queen": "kqk.uftb", "rook": "krk.uftb"}.get(
            piece.name, f"k{piece.name}k.uftb")
        result.append(class_record(f"K{piece.name}vK", states, phase, note,
                                   primary=piece.name,
                                   filename=single_filename))

    stateless = tuple(piece for piece in PIECES if piece.stateless)
    for first_index, first in enumerate(stateless):
        for second in stateless[first_index:]:
            if sufficient_pair(first, second, True):
                states = placement_states(first.models + second.models,
                                          first == second and first.models == 1)
                result.append(class_record(
                    f"K{first.name}{second.name}vK", states, "kings+2-stateless",
                    primary=first.name, secondary=second.name,
                    filename=f"k{first.name}{second.name}k.uftb"))
            if sufficient_pair(first, second, False):
                states = placement_states(first.models + second.models)
                # Pair order normally follows PIECES, but this exact table was
                # generated with Fisherman as the first (Ivory) material owner.
                # Keep the catalog aligned with its header so side-to-move WDL
                # columns and resume checks cannot silently swap the owners.
                opposing_first, opposing_second = first, second
                if first.name == "parasite" and second.name == "fisherman":
                    opposing_first, opposing_second = second, first
                result.append(class_record(
                    f"K{opposing_first.name}vK{opposing_second.name}", states,
                    "kings+2-stateless", primary=opposing_first.name,
                    secondary=opposing_second.name, opposing=True,
                    filename=(f"k{opposing_first.name}k{opposing_second.name}"
                              ".uftb")))
    # Ordinary stateful combinations are admitted deterministically only while
    # their conservative split-plane size fits the original 10 GiB target.
    used = sum(int(record["packed_bytes"]) for record in result)
    for record in stateful_candidates():
        size = int(record["packed_bytes"])
        if used + size <= budget:
            result.append(record)
            used += size

    # Deliberate, narrowly scoped over-budget additions. Copycat is exact only
    # while its linked half remains at the mirrored square; Bishop cannot split
    # or save one half, so this material class is closed under that invariant.
    by_name = {piece.name: piece for piece in PIECES}
    penguin_factor = pair_state_factor(by_name["bishop"], by_name["penguin"])
    requested = (
        class_record(
            "KcopycatvKbishop", compound_copycat_pair_states(),
            "kings+2-requested", primary="copycat", secondary="bishop",
            opposing=True, filename="kcopycatkbishop.uftb",
            note="linked mirrored Copycat compound; displaced/singleton states excluded"),
        class_record(
            "KpenguinvKdragon", placement_states(2) * pair_state_factor(
                by_name["penguin"], by_name["dragon"]),
            "kings+2-requested", primary="penguin", secondary="dragon",
            opposing=True, filename="kpenguinkdragon.uftb",
            note="current causal-Penguin payload supersedes the historical "
                 "Dragon-primary kdragonkpenguin alias"),
        class_record(
            "KbishopvKpenguin", placement_states(2) * penguin_factor,
            "kings+2-requested", primary="bishop", secondary="penguin",
            opposing=True, filename="kbishopkpenguin.uftb",
            note="exact causal Penguin membership supersedes legacy aura bit"),
        class_record(
            "KbishoppenguinvK", placement_states(2) * penguin_factor,
            "kings+2-requested", primary="bishop", secondary="penguin",
            filename="kbishoppenguink.uftb",
            note="exact causal Penguin membership supersedes legacy aura bit"),
        class_record(
            "KbombvKpenguin", placement_states(2) * pair_state_factor(
                by_name["bomb"], by_name["penguin"]),
            "kings+2-requested", primary="bomb", secondary="penguin",
            opposing=True, filename="kbombkpenguin.uftb",
            note="exact causal Penguin membership supersedes legacy aura bit"),
    )
    known = {str(record["filename"]) for record in result}
    result.extend(record for record in requested
                  if str(record["filename"]) not in known)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--budget", type=int, default=DEFAULT_BUDGET)
    args = parser.parse_args()
    records = inventory(args.budget)
    total = sum(int(record["packed_bytes"]) for record in records)
    if args.json:
        print(json.dumps({
            "budget": args.budget,
            "github_file_limit": GITHUB_FILE_LIMIT,
            "shard_limit": DEFAULT_SHARD_LIMIT,
            "classes": records,
            "packed_bytes": total,
            "fits_without_entropy_compression": total <= args.budget,
        }, indent=2))
        return

    for phase, grouped in itertools.groupby(records, key=lambda item: item["phase"]):
        group = list(grouped)
        size = sum(int(item["packed_bytes"]) for item in group)
        print(f"{phase}: {len(group)} classes, {size / 1024**3:.3f} GiB")
    print(f"total: {len(records)} classes, {total / 1024**3:.3f} GiB")
    print(f"baseline budget: {args.budget / 1024**3:.3f} GiB")
    print(f"authorized ceiling: {AUTHORIZED_BUDGET / 1024**3:.3f} GiB")
    if total > AUTHORIZED_BUDGET:
        print("exceeds authorized ceiling")
    elif total > args.budget:
        print("uses approved narrow overrun")
    else:
        print("fits conservative budget")


if __name__ == "__main__":
    main()
