#!/usr/bin/env python3
"""Print side-to-move WDL splits for packed Ultimate tablebases."""

from __future__ import annotations

import argparse
from collections import Counter
from functools import lru_cache
import hashlib
import json
import math
from pathlib import Path
import struct

import ultimate_tablebase_shards as shards


MAGIC = b"UFTB1\0\0\0"
REACHABILITY = Path(__file__).resolve().parents[2] / "tablebases" / "reachability.json"
GIANT_CODEC_STATUS = (Path(__file__).resolve().parents[2] / "tablebases" /
                      "giant_codec_regeneration.json")
BYTE_RESULTS = tuple(
    tuple(sum(((byte >> (slot * 2)) & 3) == result for slot in range(4))
          for result in range(4))
    for byte in range(256))


@lru_cache(maxsize=1)
def reachability_catalog() -> dict[str, object]:
    if not REACHABILITY.exists():
        return {}
    document = json.loads(REACHABILITY.read_text())
    if document.get("version") != 1:
        raise ValueError(f"{REACHABILITY}: unsupported reachability catalog version")
    return dict(document.get("files", {}))


@lru_cache(maxsize=1)
def giant_codec_catalog() -> dict[str, object]:
    """Load the fail-closed inventory for folded Giant anchor payloads."""
    if not GIANT_CODEC_STATUS.exists():
        raise ValueError(f"{GIANT_CODEC_STATUS}: missing Giant codec inventory")
    document = json.loads(GIANT_CODEC_STATUS.read_text())
    if (document.get("version") != 1 or
            document.get("codec") !=
            "giant-lower-left-horizontal-reflection-v2"):
        raise ValueError(
            f"{GIANT_CODEC_STATUS}: unsupported Giant codec inventory")
    files = document.get("files")
    if not isinstance(files, dict):
        raise ValueError(f"{GIANT_CODEC_STATUS}: files is not an object")
    return files


def require_current_giant_codec(path: Path,
                                digest: str | None = None) -> None:
    """Reject every folded Giant table not regenerated by anchor-v2.

    README cached-row reuse calls this without a digest, so a known stale
    payload cannot evade validation merely because its mtime is old.
    ``summary()`` supplies the logical SHA and additionally authenticates each
    verified replacement.
    """
    record = giant_codec_catalog().get(path.name)
    if record is None:
        return
    if not isinstance(record, dict):
        raise ValueError(f"{GIANT_CODEC_STATUS}: malformed {path.name} record")
    status = record.get("status")
    if status != "verified-anchor-v2":
        raise ValueError(
            f"{path}: stale Giant anchor-v1 payload; regenerate with the "
            f"command in {GIANT_CODEC_STATUS}")
    expected = record.get("current_sha256")
    if digest is not None and digest != expected:
        raise ValueError(f"{path}: Giant anchor-v2 SHA-256 binding is stale")


def audited_counts(path: Path, data: bytes, field: str,
                   digest: str | None = None) -> list[list[int]] | None:
    record = reachability_catalog().get(path.name)
    if not isinstance(record, dict):
        return None
    if record.get("sha256") != (digest or hashlib.sha256(data).hexdigest()):
        raise ValueError(f"{path}: stale native reachability audit")
    counts = record.get(field)
    if counts is None:
        return None
    if (not isinstance(counts, list) or len(counts) != 2 or
            any(not isinstance(side, list) or len(side) != 4 for side in counts)):
        raise ValueError(f"{path}: malformed native reachability audit")
    return [[int(value) for value in side] for side in counts]


def kings_for(index: int, count: int, substates: int) -> tuple[int, int]:
    placements = count // substates
    placement = index // substates
    if placements == 985_920:
        placement //= 78
        black_rank = placement % 79
        placement //= 79
        white = placement % 80
        black = black_rank + (black_rank >= white)
        return white, black
    pair_states = 3_003 if placements == 18_978_960 else 78 * 77
    placement //= pair_states
    black_rank = placement % 79
    placement //= 79
    white_rank = placement % 40
    white = (white_rank // 4) * 8 + white_rank % 4
    black = black_rank + (black_rank >= white)
    return white, black


def adjacent(first: int, second: int) -> bool:
    return max(abs(first % 8 - second % 8), abs(first // 8 - second // 8)) == 1


def rank_excluding(square: int, occupied: tuple[int, ...]) -> int:
    return square - sum(item < square for item in occupied)


def encode_four(side: int, white: int, black: int, first: int, second: int) -> int:
    if white % 8 >= 4:
        white = (white // 8) * 8 + 7 - white % 8
        black = (black // 8) * 8 + 7 - black % 8
        first = (first // 8) * 8 + 7 - first % 8
        second = (second // 8) * 8 + 7 - second % 8
    white_rank = (white // 8) * 4 + white % 8
    black_rank = rank_excluding(black, (white,))
    first_rank = rank_excluding(first, (white, black))
    second_rank = rank_excluding(second, (white, black, first))
    return ((((side * 40 + white_rank) * 79 + black_rank) * 78 + first_rank) * 77
            + second_rank)


def count_results(wdl: bytes, begin: int, end: int) -> list[int]:
    """Count packed two-bit WDL values in [begin, end) without a Python state loop."""
    totals = [0, 0, 0, 0]
    while begin < end and begin % 4:
        totals[(wdl[begin // 4] >> ((begin % 4) * 2)) & 3] += 1
        begin += 1
    aligned_end = end - (end % 4)
    if begin < aligned_end:
        for byte, occurrences in Counter(wdl[begin // 4:aligned_end // 4]).items():
            for result in range(4):
                totals[result] += BYTE_RESULTS[byte][result] * occurrences
        begin = aligned_end
    while begin < end:
        totals[(wdl[begin // 4] >> ((begin % 4) * 2)) & 3] += 1
        begin += 1
    return totals


def count_substates(wdl: bytes, begin: int, end: int, substates: int,
                    selected: set[int]) -> list[int]:
    """Count results whose per-placement substate belongs to ``selected``."""
    totals = [0, 0, 0, 0]
    while begin < end and begin % 4:
        if begin % substates in selected:
            totals[(wdl[begin // 4] >> ((begin % 4) * 2)) & 3] += 1
        begin += 1
    aligned_end = end - end % 4
    period = substates // math.gcd(substates, 4)
    first_byte = begin // 4
    last_byte = aligned_end // 4
    for phase in range(period):
        byte_index = first_byte + phase
        if byte_index >= last_byte:
            continue
        frequencies = Counter(wdl[byte_index:last_byte:period])
        slot_selected = tuple(
            (byte_index * 4 + slot) % substates in selected for slot in range(4))
        for byte, occurrences in frequencies.items():
            for slot, include in enumerate(slot_selected):
                if include:
                    totals[(byte >> (slot * 2)) & 3] += occurrences
    begin = aligned_end
    while begin < end:
        if begin % substates in selected:
            totals[(wdl[begin // 4] >> ((begin % 4) * 2)) & 3] += 1
        begin += 1
    return totals


STATE_FACTORS = {
    3: 2,   # Pawn
    7: 10,  # Berserker
    11: 2,  # Ghost
    14: 2,  # Penguin inactive / active freeze aura
    19: 4,  # Sniper
    20: 2,  # Prince
    21: 4,  # Checker / CheckerKing x ordinary/forced
}


GIANT = 23


def giant_footprint(anchor: int) -> int:
    """Return the native 2x2 Giant footprint, or zero for an invalid anchor."""
    if anchor % 8 == 7 or anchor // 8 == 9:
        return 0
    return ((1 << anchor) | (1 << (anchor + 1)) |
            (1 << (anchor + 8)) | (1 << (anchor + 9)))


@lru_cache(maxsize=None)
def giant_invalid_placements(placements: int, giant_models: int) -> int:
    """Count invalid Giant geometries in one side-to-move placement half.

    Invalid geometries are written as draw sentinels by the generator.  Count
    them from the codec domain instead of walking the WDL plane: legality is
    entirely geometric and identical for both sides to move.
    """
    if giant_models not in (1, 2):
        return 0
    if placements == 985_920:
        if giant_models != 1:
            raise ValueError("K+K+1 cannot contain two Giant models")
        white_squares = range(80)
        models_per_king_pair = 78
        identical = False
    elif placements in (37_957_920, 18_978_960):
        white_squares = ((rank // 4) * 8 + rank % 4 for rank in range(40))
        models_per_king_pair = 78 * 77 if placements == 37_957_920 else 3_003
        identical = placements == 18_978_960
        if identical and giant_models != 2:
            raise ValueError("identical four-model codec requires two Giants")
    else:
        raise ValueError(f"unsupported Giant placement count {placements}")

    invalid = 0
    for white in white_squares:
        for black in range(80):
            if black == white:
                continue
            kings = (1 << white) | (1 << black)
            valid = [giant_footprint(anchor) for anchor in range(80)
                     if anchor != white and anchor != black]
            valid = [mask for mask in valid if mask and not (mask & kings)]
            if giant_models == 1:
                legal = len(valid) if placements == 985_920 else len(valid) * 74
            else:
                legal_ordered = sum(not (first & second)
                                    for first in valid for second in valid)
                legal = legal_ordered // 2 if identical else legal_ordered
            invalid += models_per_king_pair - legal
    return invalid


def add_giant_geometry_artifacts(
        count: int, substates: int, primary: int, secondary: int,
        illegal: list[list[int]]) -> None:
    giant_models = int(primary == GIANT) + int(secondary == GIANT)
    if not giant_models:
        return
    placements = count // substates
    invalid = giant_invalid_placements(placements, giant_models) * substates
    for side in range(2):
        illegal[side][3] += invalid


def continuation_mismatches(primary: int, secondary: int, secondary_color: int,
                            substates: int, side: int) -> set[int]:
    primary_factor = STATE_FACTORS.get(primary, 1)
    secondary_factor = STATE_FACTORS.get(secondary, 1)
    if primary_factor * secondary_factor != substates:
        return set()
    result: set[int] = set()
    for combined in range(substates):
        first = combined // secondary_factor
        second = combined % secondary_factor
        primary_forced = ((primary == 20 and first == 1) or
                          (primary == 21 and first % 2 == 1))
        secondary_forced = ((secondary == 20 and second == 1) or
                            (secondary == 21 and second % 2 == 1))
        if ((primary_forced and side != 0) or
                (secondary_forced and side != secondary_color)):
            result.add(combined)
    return result


def unobservable_sniper_cooldowns(primary: int, secondary: int,
                                  substates: int) -> set[int]:
    """Return combined substates with pre-ChangeTurn Sniper cooldown 3."""
    primary_factor = STATE_FACTORS.get(primary, 1)
    secondary_factor = STATE_FACTORS.get(secondary, 1)
    if primary_factor * secondary_factor != substates:
        return set()
    result: set[int] = set()
    for combined in range(substates):
        first = combined // secondary_factor
        second = combined % secondary_factor
        if (primary == 19 and first == 3) or (secondary == 19 and second == 3):
            result.add(combined)
    return result


def checker_forced_without_jump_artifacts(
        wdl: bytes, count: int, substates: int,
        primary: int, secondary: int, secondary_color: int,
        owns_material: tuple[bool, bool], illegal: list[list[int]]) -> None:
    """Exclude forced Checker states that have no legal continued capture.

    The admitted stateful inventory currently has one Checker class:
    K+Bomb+Checker vs K, with both extras owned by Ivory. A forced chain can
    enter that four-model class from a larger endgame only when the remaining
    Black King is immediately jump-capturable. Enumerating those sparse valid
    geometries is much cheaper than walking the 151.8-million-state plane.
    """
    if not (primary == 8 and secondary == 21 and secondary_color == 0 and
            count // substates == 37_957_920 and substates == 4):
        return
    side = 0
    forced = {1, 3}
    forced_totals = count_substates(wdl, 0, count // 2, substates, forced)
    forced_adjacent_loss = 0
    for begin, end in adjacent_ranges(count, substates, side):
        forced_adjacent_loss += count_substates(
            wdl, begin, end, substates, forced)[2]
    valid = [0, 0, 0, 0]
    valid_adjacent_loss = 0
    white_squares = ((rank // 4) * 8 + rank % 4 for rank in range(40))
    for white in white_squares:
        for black in range(80):
            if black == white:
                continue
            for bomb in range(80):
                if bomb == white or bomb == black:
                    continue
                occupied = {white, black, bomb}
                for checker_substate, directions in (
                    (1, ((-1, 1), (1, 1))),
                    (3, ((-1, -1), (1, -1), (-1, 1), (1, 1))),
                ):
                    for file_delta, rank_delta in directions:
                        checker_file = black % 8 - file_delta
                        checker_rank = black // 8 - rank_delta
                        landing_file = black % 8 + file_delta
                        landing_rank = black // 8 + rank_delta
                        if not (0 <= checker_file < 8 and 0 <= checker_rank < 10 and
                                0 <= landing_file < 8 and 0 <= landing_rank < 10):
                            continue
                        checker = checker_rank * 8 + checker_file
                        landing = landing_rank * 8 + landing_file
                        if checker in occupied or landing in occupied:
                            continue
                        placement = encode_four(side, white, black, bomb, checker)
                        index = placement * substates + checker_substate
                        result = (wdl[index // 4] >> ((index % 4) * 2)) & 3
                        valid[result] += 1
                        if adjacent(white, black) and result == 2:
                            valid_adjacent_loss += 1
                        break
    for result in (1, 2, 3):
        illegal[side][result] += forced_totals[result] - valid[result]
    # Material-owner adjacent losses were already classified by the generic
    # geometry pass. Only the invalid forced portion overlaps this addition.
    illegal[side][2] -= forced_adjacent_loss - valid_adjacent_loss


def adjacent_ranges(count: int, substates: int, side: int):
    """Yield contiguous state ranges for every adjacent canonical King pair."""
    placements = count // substates
    if placements == 985_920:
        white_squares = range(80)
        material_placements = 78
    elif placements == 18_978_960:
        white_squares = ((rank // 4) * 8 + rank % 4 for rank in range(40))
        material_placements = 3_003
    else:
        if placements != 37_957_920:
            raise ValueError(f"unsupported placement count {placements}")
        white_squares = ((rank // 4) * 8 + rank % 4 for rank in range(40))
        material_placements = 78 * 77
    side_placements = placements // 2
    for white in white_squares:
        for black in range(80):
            if black == white or not adjacent(white, black):
                continue
            black_rank = black - (black > white)
            placement = (side * side_placements +
                         (white if placements == 985_920 else
                          (white // 8) * 4 + white % 8) * 79 * material_placements +
                         black_rank * material_placements)
            begin = placement * substates
            yield begin, begin + material_placements * substates


def add_penguin_reachability_artifacts(
        wdl: bytes, count: int, substates: int,
        owns_material: tuple[bool, bool], illegal: list[list[int]]) -> None:
    """Separate impossible K+Penguin-v-K causal freeze/turn states.

    An active aura must freeze at least one adjacent model. If it freezes the
    lone enemy King, that King receives the next turn and either moves (which
    detaches it from the aura) or the game ends; the turn cannot return to the
    Penguin owner with that King still frozen. An inactive Penguin cannot
    attack, so its only dense-index wins with adjacent Kings are unreachable
    geometry rather than genuine winning Penguin positions.
    """
    if count // substates != 985_920:
        raise ValueError("Penguin reachability currently requires a K+K+1 codec")
    for placement in range(count // substates):
        rest = placement
        attacker_rank = rest % 78
        rest //= 78
        black_rank = rest % 79
        rest //= 79
        white = rest % 80
        side = rest // 80
        black = black_rank + (black_rank >= white)
        low, high = sorted((white, black))
        penguin = attacker_rank
        if penguin >= low:
            penguin += 1
        if penguin >= high:
            penguin += 1
        kings_adjacent = adjacent(white, black)
        adjacent_white = adjacent(penguin, white)
        adjacent_black = adjacent(penguin, black)
        for substate in range(substates):
            index = placement * substates + substate
            result = (wdl[index // 4] >> ((index % 4) * 2)) & 3
            if substates == 2:
                # Legacy payloads represented only inactive/full-current-aura.
                freezes_white = bool(substate) and adjacent_white
                freezes_black = bool(substate) and adjacent_black
                locally_impossible = bool(substate) and not (
                    adjacent_white or adjacent_black)
            elif substates == 4:
                # Exact v4 causal membership bits: White King, Black King.
                freezes_white = bool(substate & 1)
                freezes_black = bool(substate & 2)
                locally_impossible = ((freezes_white and not adjacent_white) or
                                      (freezes_black and not adjacent_black))
            else:
                raise ValueError("unexpected K+Penguin-v-K substate factor")
            impossible_turn = side == 0 and freezes_black
            adjacent_penguin_decisive = (kings_adjacent and
                ((side == 0 and result == 1) or (side == 1 and result == 2)))
            if not (locally_impossible or impossible_turn or adjacent_penguin_decisive):
                continue
            general_artifact = kings_adjacent and (
                (result == 1 and not owns_material[side]) or
                (result == 2 and owns_material[side]))
            if not general_artifact:
                illegal[side][result] += 1


def summary(path: Path, data: bytes | None = None,
            digest: str | None = None) -> tuple[list[list[int]], list[list[int]]]:
    if data is None:
        data = shards.read_logical(path)
    magic, version, piece, count, _edges = struct.unpack_from("<8sIIII", data)
    if magic != MAGIC or version not in (4, 5, 6, 7):
        raise ValueError(f"{path}: summary requires packed v4-v7")
    substates, wdl_bytes, dtw_bytes, exceptions = struct.unpack_from("<IIII", data, 24)
    offset = (40 + (8 if version >= 5 else 0) +
              (8 if version >= 6 else 0) + (8 if version >= 7 else 0))
    wdl = data[offset:offset + wdl_bytes]
    if len(wdl) != wdl_bytes or dtw_bytes != count:
        raise ValueError(f"{path}: invalid plane sizes")
    totals = [count_results(wdl, side * count // 2, (side + 1) * count // 2)
              for side in range(2)]
    native_full = audited_counts(path, data, "necessary_reachability", digest)
    native_safety = audited_counts(
        path, data, "ordinary_predecessor_safety", digest) if native_full is None else None
    illegal = native_full or native_safety or [[0, 0, 0, 0] for _ in range(2)]
    # Canonical tables always assign the primary material to Ivory. In same-
    # team classes Onyx is bare; in opposing v5+ classes Onyx owns the
    # secondary material as well.
    secondary = -1
    secondary_color = 0
    if version >= 5:
        secondary, secondary_color = struct.unpack_from("<II", data, 40)
    if (piece == GIANT or secondary == GIANT) and count // substates != 985_920:
        require_current_giant_codec(
            path, digest or hashlib.sha256(data).hexdigest())
    owns_material = (True, secondary_color == 1)
    if native_full is not None:
        expected_size = offset + wdl_bytes + dtw_bytes + exceptions * 6
        if len(data) != expected_size:
            raise ValueError(f"{path}: trailing or truncated packed data")
        return totals, illegal
    # Audited ordinary classes use Position's complete, color-specific royal
    # safety simulation. Until each stateful class has a unioned native audit,
    # retain the older narrow adjacent-King annotation as a conservative
    # fallback; its special causal predicates below still catch forced phases.
    count_adjacent_as_illegal = native_safety is None and piece != 1
    if count_adjacent_as_illegal:
        for side in range(2):
            artifact = 2 if owns_material[side] else 1
            for begin, end in adjacent_ranges(count, substates, side):
                illegal[side][artifact] += count_results(wdl, begin, end)[artifact]
    if piece == 14 and secondary == -1:  # solo Penguin / SimulatedFreeze
        add_penguin_reachability_artifacts(wdl, count, substates,
                                           owns_material, illegal)
    for side in range(2):
        mismatches = continuation_mismatches(
            piece, secondary, secondary_color, substates, side)
        if not mismatches:
            continue
        mismatch_counts = count_substates(
            wdl, side * count // 2, (side + 1) * count // 2,
            substates, mismatches)
        # Adjacent outcome artifacts were already counted above. Subtract the
        # intersection so each unreachable record appears exactly once.
        overlap_result = 2 if owns_material[side] else 1
        overlap = 0
        if count_adjacent_as_illegal:
            for begin, end in adjacent_ranges(count, substates, side):
                overlap += count_substates(
                    wdl, begin, end, substates, mismatches)[overlap_result]
        for result in (1, 2, 3):
            illegal[side][result] += mismatch_counts[result]
        illegal[side][overlap_result] -= overlap
    cooldown_artifacts = unobservable_sniper_cooldowns(piece, secondary, substates)
    if cooldown_artifacts:
        for side in range(2):
            counts = count_substates(
                wdl, side * count // 2, (side + 1) * count // 2,
                substates, cooldown_artifacts)
            overlap_result = 2 if owns_material[side] else 1
            overlap = 0
            if count_adjacent_as_illegal:
                for begin, end in adjacent_ranges(count, substates, side):
                    overlap += count_substates(
                        wdl, begin, end, substates,
                        cooldown_artifacts)[overlap_result]
            for result in (1, 2, 3):
                illegal[side][result] += counts[result]
            illegal[side][overlap_result] -= overlap
    checker_forced_without_jump_artifacts(
        wdl, count, substates, piece, secondary, secondary_color,
        owns_material, illegal)
    add_giant_geometry_artifacts(count, substates, piece, secondary, illegal)
    expected_size = offset + wdl_bytes + dtw_bytes + exceptions * 6
    if len(data) != expected_size:
        raise ValueError(f"{path}: trailing or truncated packed data")
    return totals, illegal


def result_cell(total: int, illegal: int) -> str:
    legal = total - illegal
    return f"{legal:,}" + (f" ({illegal:,})" if illegal else "")


def cell(counts: list[int], illegal: list[int]) -> str:
    return " / ".join(result_cell(counts[result], illegal[result])
                      for result in (1, 2, 3))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("files", nargs="+", type=Path)
    args = parser.parse_args()
    for path in args.files:
        totals, illegal = summary(path)
        print(f"{path.name}\t{cell(totals[0], illegal[0])}\t{cell(totals[1], illegal[1])}")


if __name__ == "__main__":
    main()
